apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    kustomize:
      commonLabels:
        controller: argocd
      commonAnnotations:
        beep: boop
    repoURL: https://github.com/Faithtosin/homelab-argocd.git
    targetRevision: HEAD
    path: argocd/overlays
  destination:
    server: https://kubernetes.default.svc
    #namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
